apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: naveenlb777
  name: naveenlb777
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: naveenlb777
  type: NodePort
status:
  loadBalancer: {}
